defaults:
  poll_interval: 300

stacks:
  - name: arrgh-proton
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/arrgh-proton

  - name: jellyfin
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/jellyfin

  - name: immich
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/immich
