repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt (local)
        entry: shfmt
        language: system
        types: [shell]
        args: ["-i", "2", "-w"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
