defaults:
  poll_interval: 300

stacks:
  - name: vaultwarden
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/vaultwarden
    env_file: /opt/steward/config/vaultwarden.env

  - name: nextcloud
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/nextcloud
    env_file: /opt/steward/config/nextcloud.env

  - name: mealie
    repo: https://github.com/meetthecarsons/hosted-services.git
    path: stacks/mealie
    env_file: /opt/steward/config/mealie.env
