services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    pull_policy: always
    restart: unless-stopped
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - /opt/data/minecraft-bedrock/data:/data
    stdin_open: true
    tty: true
