global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - 'tardis.eland-wyrm.ts.net:9100'
          - 'crafty.eland-wyrm.ts.net:9100'
          - 'galileo.eland-wyrm.ts.net:9100'

  - job_name: cadvisor
    static_configs:
      - targets: ['localhost:8085']

  - job_name: frigate
    metrics_path: /api/metrics
    static_configs:
      - targets: ['galileo.eland-wyrm.ts.net:5000']
